### ISSUE TITLE
Feature: Logistic regression model

### ISSUE THREAD

**Issue by UtkarshGoelUT** [PEC-CSS/slowmokit#15]
Implement a logistic regression model

**Comment by YashitaBansal** [comment]
I would like to resolve this issue

**Comment by UtkarshGoelUT** [comment]
Sarthak is already working on this under the following [PR](https://github.com/PEC-CSS/slowmokit/pull/31), but there are some issues. You can still try doing it; I will also assign it to you. Make sure to consider the comments in the above PR.

**Comment by Sar-thak-3** [comment]
I'm interested in this, kindly assign it to me!

**Comment by uttammittal02** [comment]
Ok done
