### ISSUE TITLE
Implement Mean-Squared Error

### ISSUE THREAD

**Issue by uttammittal02** [PEC-CSS/slowmokit#34]

**Comment by Chanpreetk03** [comment]
I would like to work on this issue

**Comment by uttammittal02** [comment]
> I would like to work on this issue

Ok....assigning you this issue

**Comment by uttammittal02** [comment]
> I would like to work on this issue

Any updates over this?

**Comment by Chanpreetk03** [comment]
Unassigned myself as won't be able to work on this issue. Sorry for the inconvenience.

**Comment by YashitaBansal** [comment]
Pls assign it to me.
