### ISSUE TITLE
Implement addition and subtraction of matrix with a scalar

### ISSUE THREAD

**Issue by Ishwarendra** [PEC-CSS/slowmokit#64]
- Overload `operator+` `operator-` and  `operator *`. Function signatures are present in [`matrix.h`](https://github.com/PEC-CSS/slowmokit/blob/main/src/slowmokit/ducks/matrix/matrix.hpp) already at Line-145, 146, 155 and 156.
- Also overload `operator +=` and `operator -=` for a matrix and scalar (Function signature for this is not present so add that in [`matrix.h`](https://github.com/PEC-CSS/slowmokit/blob/main/src/slowmokit/ducks/matrix/matrix.hpp) too.)

**Comment by Modernbeast02** [comment]
Assign it to me please.
