### ISSUE TITLE
Implement matmul, subtract, add function.

### ISSUE THREAD

**Issue by Ishwarendra** [PEC-CSS/slowmokit#81]
- Add function signature for each function inside the `Matrix` class in [`matrix.hpp`](https://github.com/PEC-CSS/slowmokit/blob/main/src/slowmokit/ducks/matrix/matrix.hpp) and also implement in [`matrix.cpp`](https://github.com/PEC-CSS/slowmokit/blob/main/src/slowmokit/ducks/matrix/matrix.hpp).

- Function specifications:
    - `matmul:` Multiplies two **Matrices**. A Matrix and a scalar is not allowed. Also throw appropriate exception if matrix dimension are not compatible for multiplication.
    - `add:` This function will have two overloads one which will add matrix and scalar and the other one for two matrices. Throw appropriate exceptions if matrix have incompatible dimensions.
    - `subtract:` Everything same as `add` function but you should do subtraction instead of addition.

- Don't implement from scratch, use the already implemented functions `operator +=`, `operator -=` and `operator *=`. This way you will not have to worry about throwing appropriate exceptions as the already implemented function will do it for you.

- Don't forget to add comments above each function signature you add in [`matrix.hpp`](https://github.com/PEC-CSS/slowmokit/blob/main/src/slowmokit/ducks/matrix/matrix.hpp). Avoid adding comments in [`matrix.cpp`](https://github.com/PEC-CSS/slowmokit/blob/main/src/slowmokit/ducks/matrix/matrix.cpp) unless very important.

**Comment by Modernbeast02** [comment]
I want to work on this. Plz assign it to me.

**Comment by Ishwarendra** [comment]
Assigned
